### ISSUE TITLE
Why use Objective-C(++) with an Android app??

### ISSUE THREAD

**Issue by PPPDUD** [jdev082/mcatalyst2#1]

**Comment by jdev082** [comment]
Catalyst Mobile is being developed for both Android and iOS (although don't expect to see it on the app store).

**Comment by PPPDUD** [comment]
Oh. If I had an iPhone, how would I sideload it?

**Comment by jdev082** [comment]
> Oh. If I had an iPhone, how would I sideload it?
> 

Jailbreak it

**Comment by PPPDUD** [comment]
Official software that isn’t from a crazy person should not require severe
modification to the operating system of a target device.

**Comment by jdev082** [comment]
> Official software that isn’t from a crazy person should not require severe modification to the operating system of a target >device.
>
How many times must I repeat myself. Catalyst, as a free and non-funded project. In turn, gets $0 allocated to it's development. This includes being uploaded to app stores. Google Play won't be such an issue though, as it's a one time fee of $25. **APPLE ON THE OTHER HAND IS $99 PER YEAR!** Which I, in no circumstance, have the ability to pay. Especially since again, Catalyst makes me no profit. None of my software does, and that in turn means a better experience for the user.

**Comment by PPPDUD** [comment]
How is potentially bricking their phones a good experience? Can you not ask
for donations??

**Comment by jdev082** [comment]
My point is, adding advertisements decreases user experience. As for donations, this is not a viable option and the reasoning behind this **will not under any circumstance be disclosed**. Also, your lucky I am building this program for Apple software anyway. Because in a majority of instances, I don't build for apple operating systems. I simply cannot endure the costs of uploading to the apple app store. Nor do I have the time to abide by their guidelines. Simple as that.

**Comment by PPPDUD** [comment]
Why don't you make a website then? Surely you can afford to host a proxy,
right?

**Comment by jdev082** [comment]
> Why don't you make a website then? Surely you can afford to host a proxy,
> right?
> 
Doesn't fit in my budget. Also, https://getcatalyst.eu.org

**Comment by PPPDUD** [comment]
What about a proxy?

**Comment by jdev082** [comment]
> What about a proxy?
> 
For what?

**Comment by PPPDUD** [comment]
For browsing without the restrictions.

**Comment by jdev082** [comment]
> For browsing without the restrictions.
> 
Wrong kind of restriction. Also, I can't afford to upload.

**Comment by PPPDUD** [comment]
You can't even afford a website?

**Comment by jdev082** [comment]
I have a website, I literally JUST linked it. Also, nothing I host is hosted on my hardware.  You are under the assumption that I have money, I do not.
